### ISSUE TITLE
[FEATURE] Allow user-configurable FPS/Bitrate/Port/Host IP

### ISSUE THREAD

**Issue by puterboy** [TheSpaghettiDetective/OctoPrint-Obico#171]
OctoPrint/Obico is used across a broad range of computational power (e.g., Pi Zero vs. Pi4 vs. future even more powerful flavors) and bandwidth situations (e.g., wired GigE vs. WiFi vs. Mobile) -- yet the key parameters that govern power and bandwidth are one size fits all. This is especially true in compatible mode which is computationally intensive. 
Also, port is fixed to 8080 which is a very common web port and may already be in use.

Suggestion is to allow the following parameters (perhaps along with other relevant ones that I missed) to be set as variables in either the Octoprint or the Obico UI

1. FPS - (particularly for Compatible mode, ffmpeg_from_jmpeg Currently fixed at 25 (Premium) or 5 (Basic) --> allow arbitrary choice (subject potentially to limitations based on pro vs. not pro)
2.  Resolution - currently generally read from the camera -> allow resolution to be decreased as part of the transcoding to save bandwidth
3. Bitrate - allow setting of bitrate (a proxy for image quality) again to optimize bandwidth
4. Port - currently fixed at 8080 (but maybe this port is needed for another app - plus Octoprint allows specifying the port for webstream and snapshots already)
5. "Throttling" of flask mpeg restreaming (when using Premium/Basic) -- currently there is a fixed 0.15 sec time delay --> change to ability to set a fps maximum (use timestamps to insert a variable wait to keep framerate under the max that is set)
6. Host IP - Currently the host restreams to 127.0.0.1 (which is a bug and should be 0.0.0.0) -- but why not allow arbitrary
Potentially also Host for flask restreaming (now defaults to 127.0.0.1 -- which is a bug and should be 0.0.0.0 -- but why not allow arbitrary?)
7. "Snapshot" streaming rate for the "0.1 FPS mode" -- change fixed snapshot every 10 seconds to snapshot every X seconds (where X can be < 1 too)

All of these added configurations should be trivial to add -- just change to a variable (rather than fixed constant) in the webcam_stream.py code and create a textbox in the UI +/- some minimal sanity checking of the entries.

Note that the FPS for Compatible mode is especially important in case you have an underpowered PI and the 5/25 fixed options are crunching your CPU.

Seems simple :)

**Comment by kennethjiang** [comment]
I have to close this issue as you brought up too many things to be addressable in 1 issue.

You already opened other issues for feature request such as configurable port. Please do file duplicates.
