### ISSUE TITLE
[Feature] Support for Python 3

### ISSUE THREAD

**Issue by r4wk** [TheSpaghettiDetective/OctoPrint-Obico#199]
**Is your feature request related to a problem? Please describe.**
Yes, can't use the latest version of OctoPrint with Obico as it requires Python 3

**Describe the solution you'd like**
Add Python 3 support

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by kennethjiang** [comment]
Obico does support python 3. Did you run into any problems related to python 3 compatibility?

**Comment by r4wk** [comment]
You're right, user error. Sorry about that.
